version: '3.8'

networks:
  monitoring_network:
    driver: bridge

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./provisioning/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring_network

  manticore_exporter:
    build:
      context: https://github.com/manticoresoftware/manticoresearch-prometheus.git
      dockerfile: Dockerfile
    container_name: manticore_exporter
    env_file: "manticore.env"
    ports:
      - "8081:8081"
    networks:
      - monitoring_network
